import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { getPosts } from '../lib/api'

export interface Post {
  _id: any
  title: string
  brief: any
}

interface Props {
  posts: Post[]
}

const Home: NextPage<Props> = (props) => {

  const { posts } = props 


  return (
    <div className={styles.container}>
      <Head>
        <title>apu314</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      {posts.map((post: Post) => {
          return (
            <div key={post._id}>
              <h1>{post.title}</h1>
              <p>{post.brief}</p>
            </div>
          );
        })}
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (ctx) => {
  const posts = await getPosts()

  return {
    props: {
      posts: posts
    }
  }
}

export default Home
