name: Build and Deploy Cron

on:
  schedule:
    - cron: 45 2 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy hook request
        run: curl -X POST -d {} ${{secrets.BUILD_DEPLOY_HOOK}}
